# Generated by Django 5.1.5 on 2025-01-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='botuser',
            table='bot_users',
        ),
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
    ]
