from .languages import languages_keyboard
from .get_fullname import get_fullname_keyboard
from .get_contact import get_contact_keyboard
from .get_location import location_keyboard
from .main_manu import main_menu_keyboard
from .ready_game import ready_game_keyboard
from .settings import settings_keyboard
from .ready_robot_game import ready_robot_game_keyboard
from .robot_game import robot_game_keyboard
